// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGcakXF6dxW1ogFgyMMm5n7VS_WA1YRWc',
    appId: '1:257252220179:web:1030ded7c4cf8208b78ee6',
    messagingSenderId: '257252220179',
    projectId: 'juguemos-bef8d',
    authDomain: 'juguemos-bef8d.firebaseapp.com',
    storageBucket: 'juguemos-bef8d.firebasestorage.app',
    measurementId: 'G-235XTZBHMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxuLBkVfH4klj-99mDpbYOoEpqESPTOAY',
    appId: '1:257252220179:android:5334858a1f47c7acb78ee6',
    messagingSenderId: '257252220179',
    projectId: 'juguemos-bef8d',
    storageBucket: 'juguemos-bef8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBse23iiOlZuM-ArhMemJEXvk-Pn1jHGhc',
    appId: '1:257252220179:ios:9f86f75089a575d7b78ee6',
    messagingSenderId: '257252220179',
    projectId: 'juguemos-bef8d',
    storageBucket: 'juguemos-bef8d.firebasestorage.app',
    iosBundleId: 'com.frangonzalez.juguemos',
  );
}
